"""
Regenerate figures 1-4 with titles that contain no em-dashes
and no AI-flavored phrasing. Reads existing CSVs and re-runs the
plotting only.
"""
import os, json, warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.ensemble import RandomForestClassifier
from features import engineer_all

RNG = 42
OUT = '/home/claude/paper/results'

df = pd.read_csv('/home/claude/paper/data/training_data_2_csv_UTF.csv',
                 encoding='utf-8', on_bad_lines='skip', low_memory=False)
df = df.dropna(subset=['bot']).copy()
df['bot'] = df['bot'].astype(int)
df = df.drop_duplicates(subset=['id_str']).reset_index(drop=True)
X, behav_cols, content_cols = engineer_all(df)
y = df['bot'].values
X = X.replace([np.inf, -np.inf], np.nan).fillna(X.median(numeric_only=True))

# --- Fig 1: marginal distributions ---
sel = ['account_age_days', 'log_followers', 'log_friends', 'log_statuses',
       'friends_per_day', 'screen_name_digit_ratio',
       'default_profile', 'verified']
fig, axes = plt.subplots(2, 4, figsize=(15, 7))
for ax, f in zip(axes.flat, sel):
    h = X.loc[y==0, f]; b = X.loc[y==1, f]
    xl = f
    bins = np.linspace(min(h.min(), b.min()), max(h.max(), b.max()), 40)
    ax.hist(h, bins=bins, alpha=0.55, label='Human', density=True, color='#2b8cbe')
    ax.hist(b, bins=bins, alpha=0.55, label='Bot', density=True, color='#e34a33')
    ax.set_xlabel(xl); ax.set_ylabel('Density')
    ax.legend(fontsize=8)
fig.suptitle('Marginal distributions of selected behavioral features by class',
             fontsize=11, fontweight='bold')
plt.tight_layout()
plt.savefig(f'{OUT}/fig1_feature_distributions.png', dpi=150, bbox_inches='tight')
plt.close()

# --- Fig 2: ROC curves ---
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=RNG)
oof = {}
for name, cols in [('RF-Content', content_cols),
                   ('RF-Behavioral', behav_cols),
                   ('RF-Fusion', behav_cols + content_cols)]:
    m = RandomForestClassifier(n_estimators=300, random_state=RNG, n_jobs=-1)
    oof[name] = cross_val_predict(m, X[cols].values, y, cv=skf, method='predict_proba', n_jobs=-1)[:,1]

fig, ax = plt.subplots(figsize=(7, 6))
for name in ['RF-Content', 'RF-Behavioral', 'RF-Fusion']:
    fpr, tpr, _ = roc_curve(y, oof[name])
    auc = roc_auc_score(y, oof[name])
    ax.plot(fpr, tpr, lw=2, label=f'{name} (AUC = {auc:.3f})')
ax.plot([0, 1], [0, 1], 'k--', alpha=0.4, label='Chance')
ax.set_xlabel('False positive rate'); ax.set_ylabel('True positive rate')
ax.set_title('ROC curves under 5-fold cross-validation', fontweight='bold')
ax.legend(loc='lower right')
ax.set_xlim(0, 1); ax.set_ylim(0, 1.02)
plt.tight_layout()
plt.savefig(f'{OUT}/fig2_roc_curves.png', dpi=150, bbox_inches='tight')
plt.close()

# --- Fig 3: adversarial degradation ---
table3 = pd.read_csv(f'{OUT}/table3_adversarial_robustness.csv')
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
for ax, metric in zip(axes, ['f1', 'roc_auc']):
    for name in ['RF-Content', 'RF-Behavioral', 'RF-Fusion']:
        sub = table3[table3['model'] == name]
        ax.plot(sub['severity'], sub[metric], 'o-', lw=2, markersize=8, label=name)
    ax.set_xlabel('Feature-laundering severity (0 = clean, 1 = full)')
    ax.set_ylabel(metric.upper())
    ax.set_title(f'{metric.upper()} vs. adversarial severity')
    ax.legend(); ax.set_ylim(0, 1.02)
fig.suptitle('Classifier performance as content features are replaced with human-distribution samples',
             fontsize=11, fontweight='bold')
plt.tight_layout()
plt.savefig(f'{OUT}/fig3_adversarial_degradation.png', dpi=150, bbox_inches='tight')
plt.close()

# --- Fig 4: feature importance ---
table4 = pd.read_csv(f'{OUT}/table4_feature_importance.csv')
top_n = 15
top = table4.head(top_n).iloc[::-1]
colors = ['#2b8cbe' if fam == 'behavioral' else '#e34a33'
          for fam in top['feature_family']]
fig, ax = plt.subplots(figsize=(8.5, 6.5))
ax.barh(top['feature'], top['importance'], color=colors)
ax.set_xlabel('Importance (RF-Fusion, Gini)')
ax.set_title(f'Top {top_n} features by Gini importance\n(blue: behavioral; red: content)',
             fontweight='bold')
plt.tight_layout()
plt.savefig(f'{OUT}/fig4_feature_importance.png', dpi=150, bbox_inches='tight')
plt.close()

# --- Fig 5 already regenerated by run_extended.py; just update its title ---
from sklearn.calibration import calibration_curve
from sklearn.metrics import brier_score_loss
from sklearn.model_selection import train_test_split

X_tr, X_te, y_tr, y_te = train_test_split(df, y, test_size=0.3, random_state=RNG, stratify=y)
X_tr_feat, _, _ = engineer_all(X_tr)
X_te_feat, _, _ = engineer_all(X_te)
X_tr_feat = X_tr_feat.replace([np.inf,-np.inf],np.nan).fillna(X_tr_feat.median(numeric_only=True))
X_te_feat = X_te_feat.replace([np.inf,-np.inf],np.nan).fillna(X_te_feat.median(numeric_only=True))

rf_c = RandomForestClassifier(n_estimators=300, random_state=RNG, n_jobs=-1).fit(X_tr_feat[content_cols].values, y_tr)
rf_b = RandomForestClassifier(n_estimators=300, random_state=RNG, n_jobs=-1).fit(X_tr_feat[behav_cols].values, y_tr)
rf_f = RandomForestClassifier(n_estimators=300, random_state=RNG, n_jobs=-1).fit(X_tr_feat[behav_cols + content_cols].values, y_tr)

probs = {
    'RF-Content': rf_c.predict_proba(X_te_feat[content_cols].values)[:,1],
    'RF-Behavioral': rf_b.predict_proba(X_te_feat[behav_cols].values)[:,1],
    'RF-Fusion': rf_f.predict_proba(X_te_feat[behav_cols + content_cols].values)[:,1],
}

fig, ax = plt.subplots(figsize=(7, 6))
for name, p in probs.items():
    brier = brier_score_loss(y_te, p)
    frac_pos, mean_pred = calibration_curve(y_te, p, n_bins=10, strategy='quantile')
    ax.plot(mean_pred, frac_pos, 'o-', lw=2, label=f'{name} (Brier = {brier:.3f})')
ax.plot([0,1],[0,1], 'k--', alpha=0.4, label='Perfectly calibrated')
ax.set_xlabel('Mean predicted probability')
ax.set_ylabel('Fraction of positives')
ax.set_title('Reliability diagram for RF classifiers (held-out test set, n = 730)', fontweight='bold')
ax.legend(loc='upper left')
plt.tight_layout()
plt.savefig(f'{OUT}/fig5_calibration.png', dpi=150, bbox_inches='tight')
plt.close()

print("Regenerated figs 1-5 with clean titles")
